name: CombatTag
version: 4.2
author: cheddar262
main: com.trc202.CombatTag.CombatTag
commands:
  CombatTag:
    description: Shows the current remaining time in a tag
    aliases: ctag
    usage: /ctag